spring:
  application:
    name: auth-service
  datasource:
    url: { url }
    username: { username }
    password: { password }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

eureka:
  client:
    service-url:
      defaultZone: { defaultZone }

management:
  zipkin:
    tracing:
      endpoint: { endpoint }
  tracing:
    sampling:
      probability: 1.0

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

server:
  port: { port }